spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    url: jdbc:${POSTGRES_CONNECTION:postgresql}://${POSTGRES_HOST:db-news-system:5432}/${POSTGRES_DB:news_system}
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    contexts: demo
  data:
    redis:
      host: redis-cache
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 60m

external-api:
  comment-service:
    url: "http://comment-service:8082/api/v1"

exception-handling:
  enable: true

in-memory-cache:
  enable: true
  algorithm: LRU
  capacity: 3